import { createTestDb, type TestDb } from '../db/testing/pglite';

import { createProvider, type Provider } from './provider';

// Full-stack auth test on pglite: real migrations + real auth provider.
// Catches schema/adapter drift that unit mocks would miss.
describe('auth (email + password) on pglite', () => {
  let t: TestDb;
  let auth: Provider;

  beforeEach(async () => {
    t = await createTestDb();
    auth = createProvider(t.db, { secret: 'test-secret-not-for-prod' });
  });
  afterEach(async () => {
    await t.close();
  });

  it('sign-up creates a user and returns a session token', async () => {
    const res = await auth.api.signUpEmail({
      body: { email: 'andrea@example.com', password: 'correct-horse-battery', name: 'andrea' },
    });

    expect(res.user.email).toBe('andrea@example.com');
    expect(res.token).toBeTruthy();

    const users = await t.db.select().from(t.schema.users);
    expect(users).toHaveLength(1);
    expect(users[0]?.id).toBe(res.user.id); // uuid generated by the DB
  });

  it('sign-in succeeds with the right password', async () => {
    await auth.api.signUpEmail({
      body: { email: 'a@example.com', password: 'right-password-1', name: 'a' },
    });
    const res = await auth.api.signInEmail({
      body: { email: 'a@example.com', password: 'right-password-1' },
    });
    expect(res.token).toBeTruthy();
  });

  it('sign-in fails with a wrong password', async () => {
    await auth.api.signUpEmail({
      body: { email: 'a@example.com', password: 'right-password-1', name: 'a' },
    });
    await expect(
      auth.api.signInEmail({ body: { email: 'a@example.com', password: 'wrong-password' } }),
    ).rejects.toMatchObject({ status: 'UNAUTHORIZED' });
  });

  it('duplicate email sign-up is rejected', async () => {
    await auth.api.signUpEmail({ body: { email: 'a@example.com', password: 'password-123', name: 'a' } });
    await expect(
      auth.api.signUpEmail({ body: { email: 'a@example.com', password: 'password-456', name: 'b' } }),
    ).rejects.toBeTruthy();
  });
});
