// The ONLY file that imports the auth vendor. Everything else consumes the
// neutral surface in ./session.ts, so the vendor can be swapped by rewriting
// this file alone (plus the client wrapper on the frontend).
import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { organization } from 'better-auth/plugins';

import { db as defaultDb } from '../db/client';
import { accounts, invitations, members, sessions, users, verifications, workspaces } from '../db/schema';

export interface AuthOptions {
  /** Session signing secret. */
  secret?: string;
  /** Public base URL of the app. */
  baseUrl?: string;
}

/** Any drizzle database the adapter accepts (node-postgres in prod, pglite in tests). */
type AdapterDb = Parameters<typeof drizzleAdapter>[0];

/** Factory — lets tests run the full auth stack against an isolated (pglite) DB. */
export function createProvider(db: AdapterDb, options: AuthOptions = {}) {
  return betterAuth({
    // Explicit injection only — the vendor's own env auto-detection is not relied upon.
    ...(options.secret && { secret: options.secret }),
    ...(options.baseUrl && { baseURL: options.baseUrl }),
    database: drizzleAdapter(db, {
      provider: 'pg',
      schema: {
        user: users,
        session: sessions,
        account: accounts,
        verification: verifications,
        organization: workspaces,
        member: members,
        invitation: invitations,
      },
    }),
    // Start with email+password only. Verification emails come later (SMTP);
    // social providers (Google) land as separate PRs.
    emailAndPassword: { enabled: true, requireEmailVerification: false },
    advanced: {
      // uuid PKs are generated by the DB (defaultRandom) — Mocco convention (non-sequential).
      database: { generateId: false },
    },
    // Workspace = organization plugin (members, roles). The invitation MODEL is
    // mapped for plugin compatibility; the invite FLOW ships later. Teams/dynamic
    // roles come later.
    plugins: [
      organization({
        organizationHooks: {
          // Slugs are case-insensitively unique at the DB (lower(slug) index);
          // normalize on create so stored slugs are always lowercase and the
          // vendor's exact-match duplicate pre-check stays meaningful.
          beforeCreateOrganization: async ({ organization: org }) => ({
            data: { ...org, slug: org.slug?.toLowerCase() },
          }),
        },
      }),
    ],
  });
}

export type Provider = ReturnType<typeof createProvider>;

const state: { provider?: Provider } = {};

/** Default instance bound to the app DB. Created lazily so builds don't need env. */
export function getProvider(): Provider {
  if (!state.provider) {
    state.provider = createProvider(defaultDb, {
      secret: process.env.AUTH_SECRET,
      baseUrl: process.env.AUTH_URL,
    });
  }
  return state.provider;
}
