import { InboundKinds, InboundSourceStatuses, inboundKindSchema } from '@mocco/common/inbound';
import { TriangleAlertIcon } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

import {
  Ago,
  CopyField,
  daysSince,
  errorMessage,
  inputClass,
  labelClass,
  Notice,
  Spinner,
  StatusBadge,
  Tones,
} from '@frontend/components/notifications/notification-ui';
import { Button } from '@frontend/components/ui/button';
import { fireAndForget } from '@frontend/lib/fire-and-forget';
import { Routes } from '@frontend/lib/routes';
import { trpc } from '@frontend/lib/trpc';
import { cn } from '@frontend/lib/utils';

import type { InboundKind, InboundSourceDto } from '@mocco/common/inbound';
import type { ReactNode } from 'react';

interface Props {
  workspaceId: string;
  isAdmin: boolean;
}

const BLANK = /^\s*$/u;
const isBlank = (value: string) => BLANK.test(value);

/** A source with no delivery for this many days gets a "gone quiet" hint. */
const QUIET_DAYS = 7;

const KIND_LABELS: Record<InboundKind, string> = {
  [InboundKinds.sentry]: 'Sentry',
  [InboundKinds.vercel]: 'Vercel',
  [InboundKinds.github]: 'GitHub',
};

/** Where the signing secret comes from, per vendor (GitHub's is generated by Mocco). */
const SECRET_HELP: Record<InboundKind, string> = {
  [InboundKinds.sentry]: 'Paste the Client Secret of your Sentry internal integration.',
  [InboundKinds.vercel]: 'Paste the secret Vercel showed when you created the webhook.',
  [InboundKinds.github]: 'Mocco generates the secret and shows it once after you create the source.',
};

/** Short per-vendor setup steps; the guide page has the full version. */
const SETUP_STEPS: Record<InboundKind, ReactNode[]> = {
  [InboundKinds.sentry]: [
    'In Sentry, open Settings → Developer Settings and create an internal integration.',
    'Set its webhook URL to this source’s ingest URL.',
    'Give it read access to issues and events, and turn on the “issue” webhook.',
    'Save, then paste the integration’s Client Secret here (Rotate secret, if you started with a placeholder).',
  ],
  [InboundKinds.vercel]: [
    'Vercel team webhooks need a Pro or Enterprise plan.',
    'In Vercel, open your team’s Settings → Webhooks and create a webhook.',
    'Select the Deployment events and your projects, and use this source’s ingest URL as the endpoint.',
    'Vercel shows the secret once: paste it here with Rotate secret.',
  ],
  [InboundKinds.github]: [
    'In GitHub, open the repository (or organization) Settings → Webhooks → Add webhook.',
    'Payload URL: this source’s ingest URL. Content type: application/json.',
    'Secret: the one Mocco showed when you created the source (Rotate secret gives you a new one).',
    'Choose the events: pushes, pull requests, issues, releases and workflow runs.',
  ],
};

const GUIDE_PAGE: Record<InboundKind, string> = {
  [InboundKinds.sentry]: 'sentry',
  [InboundKinds.vercel]: 'vercel',
  [InboundKinds.github]: 'github',
};

/** The GitHub secret Mocco generated, shown once. It lives in component state only. */
function OneTimeSecret({
  sourceName,
  secret,
  onDismiss,
}: {
  sourceName: string;
  secret: string;
  onDismiss: () => void;
}) {
  return (
    <div role="alert" className="flex flex-col gap-3 rounded-xl border border-amber-600/40 bg-amber-500/5 p-4">
      <div className="flex items-start gap-2">
        <TriangleAlertIcon aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-amber-600 dark:text-amber-400" />
        <div className="flex flex-col gap-1">
          <p className="text-sm font-semibold">Copy the webhook secret for {sourceName} now</p>
          <p className="text-sm text-muted-foreground">
            Paste it into the <span className="font-medium text-foreground">Secret</span> field of the GitHub webhook.
            Mocco stores it sealed and will not show it again; if you lose it, use Rotate secret.
          </p>
        </div>
      </div>
      <CopyField label="Webhook secret" value={secret} />
      <div>
        <Button variant="outline" size="sm" onClick={onDismiss}>
          I’ve copied it
        </Button>
      </div>
    </div>
  );
}

function SetupSteps({ kind }: { kind: InboundKind }) {
  return (
    <details className="group rounded-lg bg-muted/40 px-3 py-2 text-sm">
      <summary className="cursor-pointer text-xs font-medium text-muted-foreground select-none">
        Setup steps for {KIND_LABELS[kind]}
      </summary>
      <ol className="mt-2 flex list-decimal flex-col gap-1 pl-5 text-sm">
        {SETUP_STEPS[kind].map((step, index) => (
          // The steps are a fixed list: the index is a stable key.
          // eslint-disable-next-line @eslint-react/no-array-index-key
          <li key={index}>{step}</li>
        ))}
      </ol>
      <Link
        href={Routes.notificationsGuide(GUIDE_PAGE[kind])}
        className="mt-2 inline-block text-xs font-medium underline underline-offset-2">
        Read the full {KIND_LABELS[kind]} guide
      </Link>
    </details>
  );
}

function AddSourceForm({
  workspaceId,
  onCreated,
}: {
  workspaceId: string;
  onCreated: (created: { source: InboundSourceDto; generatedSecret: string | null }) => void;
}) {
  const utils = trpc.useUtils();
  const [kind, setKind] = useState<InboundKind>(InboundKinds.github);
  const [name, setName] = useState('');
  const [secret, setSecret] = useState('');
  const create = trpc.inbound.sources.create.useMutation({
    onSuccess: created => {
      setName('');
      setSecret('');
      onCreated(created);
      fireAndForget(utils.inbound.sources.list.invalidate({ workspaceId }));
    },
  });
  const isSecretNeeded = kind !== InboundKinds.github;
  // eslint-disable-next-line sonarjs/null-dereference -- name is a useState<string>, never null
  const trimmedName = name.trim();
  const isSecretMissing = isSecretNeeded && isBlank(secret);

  return (
    <form
      aria-label="Add a source"
      className="flex flex-col gap-3 rounded-xl border border-border p-4"
      onSubmit={event => {
        event.preventDefault();
        create.mutate({ workspaceId, kind, name: trimmedName, ...(isSecretNeeded && { secret }) });
      }}>
      <div className="flex flex-wrap items-end gap-3">
        <label className={labelClass}>
          Kind
          <select
            className={cn(inputClass, 'w-36')}
            value={kind}
            onChange={event => {
              const parsed = inboundKindSchema.safeParse(event.target.value);
              if (parsed.success) {
                setKind(parsed.data);
              }
            }}>
            {inboundKindSchema.options.map(option => (
              <option key={option} value={option}>
                {KIND_LABELS[option]}
              </option>
            ))}
          </select>
        </label>
        <label className={labelClass}>
          Name
          <input
            required
            maxLength={100}
            className={cn(inputClass, 'w-52')}
            placeholder={`${KIND_LABELS[kind]} (acme)`}
            value={name}
            onChange={event => {
              setName(event.target.value);
            }}
          />
        </label>
        {isSecretNeeded ? (
          <label className={labelClass}>
            Signing secret
            <input
              required
              type="password"
              autoComplete="off"
              spellCheck={false}
              className={cn(inputClass, 'w-64 font-mono')}
              value={secret}
              onChange={event => {
                setSecret(event.target.value);
              }}
            />
          </label>
        ) : null}
        <Button type="submit" pending={create.isPending} disabled={trimmedName === '' || isSecretMissing}>
          Create source
        </Button>
      </div>
      <p className="text-xs text-muted-foreground">
        {SECRET_HELP[kind]}
        {isSecretNeeded
          ? ' Need the ingest URL first? Enter a placeholder, copy the URL, then use Rotate secret once the vendor shows you the real one.'
          : ''}
      </p>
      {create.error === null ? null : (
        <Notice tone={Tones.danger} title="The source was not created">
          {errorMessage(create.error)}
        </Notice>
      )}
    </form>
  );
}

function RotateSecretForm({
  workspaceId,
  source,
  onRotated,
  onCancel,
}: {
  workspaceId: string;
  source: InboundSourceDto;
  onRotated: (generatedSecret: string | null) => void;
  onCancel: () => void;
}) {
  const utils = trpc.useUtils();
  const [secret, setSecret] = useState('');
  const rotate = trpc.inbound.sources.rotateSecret.useMutation({
    onSuccess: ({ generatedSecret }) => {
      onRotated(generatedSecret);
      fireAndForget(utils.inbound.sources.list.invalidate({ workspaceId }));
    },
  });
  const isGithub = source.kind === InboundKinds.github;

  return (
    <form
      aria-label={`Rotate the secret of ${source.name}`}
      className="flex flex-wrap items-end gap-2 rounded-lg bg-muted/40 p-3"
      onSubmit={event => {
        event.preventDefault();
        rotate.mutate({ workspaceId, sourceId: source.id, ...(!isGithub && { secret }) });
      }}>
      {isGithub ? (
        <p className="text-sm">
          Mocco will generate a new secret. Deliveries signed with the old one fail until you paste the new one into
          GitHub.
        </p>
      ) : (
        <label className={labelClass}>
          New signing secret
          <input
            required
            type="password"
            autoComplete="off"
            spellCheck={false}
            className={cn(inputClass, 'w-64 font-mono')}
            value={secret}
            onChange={event => {
              setSecret(event.target.value);
            }}
          />
        </label>
      )}
      <Button type="submit" size="sm" pending={rotate.isPending} disabled={!isGithub && isBlank(secret)}>
        {isGithub ? 'Generate new secret' : 'Save secret'}
      </Button>
      <Button type="button" size="sm" variant="ghost" onClick={onCancel}>
        Cancel
      </Button>
      {rotate.error === null ? null : (
        <p role="alert" className="basis-full text-xs text-destructive">
          {rotate.error.message}
        </p>
      )}
    </form>
  );
}

function SourceCard({ workspaceId, source, isAdmin }: Props & { source: InboundSourceDto }) {
  const utils = trpc.useUtils();
  const [rotating, setRotating] = useState(false);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [newSecret, setNewSecret] = useState<string | null>(null);
  const refresh = () => {
    fireAndForget(utils.inbound.sources.list.invalidate({ workspaceId }));
  };
  const pause = trpc.inbound.sources.pause.useMutation({ onSuccess: refresh });
  const resume = trpc.inbound.sources.resume.useMutation({ onSuccess: refresh });
  const remove = trpc.inbound.sources.delete.useMutation({ onSuccess: refresh });
  const isPaused = source.status === InboundSourceStatuses.paused;
  const quietDays = source.lastReceivedAt === null ? 0 : daysSince(source.lastReceivedAt);
  const isQuiet = quietDays >= QUIET_DAYS;
  const actionError = pause.error ?? resume.error ?? remove.error;

  return (
    <li className="flex flex-col gap-3 rounded-xl border border-border p-4">
      <div className="flex flex-wrap items-center gap-3">
        <span className="rounded-md border border-border px-1.5 py-0.5 text-[11px] font-semibold tracking-wide text-muted-foreground uppercase">
          {KIND_LABELS[source.kind]}
        </span>
        <h3 className="min-w-0 flex-1 truncate text-sm font-semibold">{source.name}</h3>
        {isPaused ? (
          <StatusBadge tone={Tones.neutral}>Paused</StatusBadge>
        ) : (
          <StatusBadge tone={Tones.ok}>Active</StatusBadge>
        )}
      </div>

      <div className="flex flex-col gap-1">
        <span className="text-xs font-medium text-muted-foreground">Ingest URL</span>
        <CopyField label={`Ingest URL of ${source.name}`} value={source.ingestUrl} />
      </div>

      <p className="text-xs text-muted-foreground">
        Last received:{' '}
        {source.lastReceivedAt === null ? (
          <span className="font-medium text-foreground">Never</span>
        ) : (
          <span className="font-medium text-foreground">
            <Ago date={source.lastReceivedAt} />
          </span>
        )}
        {isQuiet ? ` · no deliveries in ${quietDays} days` : ''}
        {isPaused ? ' · paused sources answer 404, so the vendor’s deliveries fail until you resume' : ''}
      </p>

      {newSecret === null ? null : (
        <OneTimeSecret
          sourceName={source.name}
          secret={newSecret}
          onDismiss={() => {
            setNewSecret(null);
          }}
        />
      )}

      {isAdmin ? (
        <div className="flex flex-wrap items-center gap-1.5">
          {isPaused ? (
            <Button
              size="sm"
              variant="outline"
              pending={resume.isPending}
              onClick={() => {
                resume.mutate({ workspaceId, sourceId: source.id });
              }}>
              Resume
            </Button>
          ) : (
            <Button
              size="sm"
              variant="outline"
              pending={pause.isPending}
              onClick={() => {
                pause.mutate({ workspaceId, sourceId: source.id });
              }}>
              Pause
            </Button>
          )}
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              setRotating(value => !value);
            }}>
            Rotate secret
          </Button>
          {confirmingDelete ? (
            <>
              <Button
                size="sm"
                variant="destructive"
                pending={remove.isPending}
                onClick={() => {
                  remove.mutate({ workspaceId, sourceId: source.id });
                }}>
                Delete source and its activity
              </Button>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => {
                  setConfirmingDelete(false);
                }}>
                Cancel
              </Button>
            </>
          ) : (
            <Button
              size="sm"
              variant="ghost"
              onClick={() => {
                setConfirmingDelete(true);
              }}>
              Delete
            </Button>
          )}
        </div>
      ) : null}
      {actionError === null ? null : (
        <p role="alert" className="text-xs text-destructive">
          {actionError.message}
        </p>
      )}
      {rotating ? (
        <RotateSecretForm
          workspaceId={workspaceId}
          source={source}
          onRotated={generatedSecret => {
            setRotating(false);
            setNewSecret(generatedSecret);
          }}
          onCancel={() => {
            setRotating(false);
          }}
        />
      ) : null}

      <SetupSteps kind={source.kind} />
    </li>
  );
}

/**
 * The Sources tab: the webhooks a workspace receives (Sentry, Vercel, GitHub), each with
 * its ingest URL to paste into the vendor, when it last received something, and its
 * pause / rotate / delete actions. A GitHub source's generated secret is shown once.
 */
export default function NotificationSources({ workspaceId, isAdmin }: Props) {
  const sourcesQuery = trpc.inbound.sources.list.useQuery({ workspaceId }, { retry: false });
  const [adding, setAdding] = useState(false);
  const [created, setCreated] = useState<{ name: string; secret: string } | null>(null);

  if (sourcesQuery.isPending) {
    return <Spinner />;
  }
  if (sourcesQuery.isError) {
    return sourcesQuery.error.data?.code === 'PRECONDITION_FAILED' ? (
      <Notice tone={Tones.warn} title="Webhook sources are not available on this Mocco server">
        The server has no encryption key for webhook secrets yet, so no source can be added. Whoever runs this Mocco
        server needs to configure it first.
      </Notice>
    ) : (
      <Notice tone={Tones.danger} title="Sources could not be loaded">
        {sourcesQuery.error.message}
      </Notice>
    );
  }

  const { sources } = sourcesQuery.data;

  return (
    <section aria-labelledby="inbound-sources" className="flex flex-col gap-3">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 id="inbound-sources" className="text-base font-semibold">
            Sources
          </h2>
          <p className="text-sm text-muted-foreground">
            Webhooks from Sentry, Vercel and GitHub. Each source has its own signed ingest URL.{' '}
            <Link href={Routes.notificationsGuide('overview')} className="underline underline-offset-2">
              How it works
            </Link>
          </p>
        </div>
        {isAdmin ? (
          <Button
            variant={adding ? 'ghost' : 'default'}
            onClick={() => {
              setAdding(value => !value);
            }}>
            {adding ? 'Close' : 'Add source'}
          </Button>
        ) : null}
      </div>
      {adding ? (
        <AddSourceForm
          workspaceId={workspaceId}
          onCreated={({ source, generatedSecret }) => {
            setAdding(false);
            setCreated(generatedSecret === null ? null : { name: source.name, secret: generatedSecret });
          }}
        />
      ) : null}
      {created === null ? null : (
        <OneTimeSecret
          sourceName={created.name}
          secret={created.secret}
          onDismiss={() => {
            setCreated(null);
          }}
        />
      )}
      {sources.length === 0 ? (
        <p className="rounded-xl border border-dashed border-border px-4 py-6 text-center text-sm text-muted-foreground">
          No sources yet.{' '}
          {isAdmin ? 'Add one to receive Sentry, Vercel or GitHub events.' : 'An owner or admin can add one.'}
        </p>
      ) : (
        <ul className="flex flex-col gap-3">
          {sources.map(source => (
            <SourceCard key={source.id} workspaceId={workspaceId} source={source} isAdmin={isAdmin} />
          ))}
        </ul>
      )}
    </section>
  );
}
