// The tools that change a workspace's webhook sources: add a GitHub source, pause and
// resume a source, and delete one.
//
// The same locks as every changing tool (`tools/deciding.ts`): the `approvals:write`
// scope, the workspace's opt-in, and a confirmation the person answers in their client
// showing exactly what would change. Then the console's rule: only an owner or admin
// (`WorkspaceScope.requireAdmin`, the check the console's `adminInboundProcedure` makes).
//
// A signing secret never enters the model's context:
// - A GitHub source's secret is generated by Mocco. The console shows it once, at
//   creation; this tool does not return it. The person gets one to paste into GitHub by
//   rotating the source's secret in the console.
// - Sentry and Vercel sources need the secret the vendor shows, and a source cannot exist
//   without one (deliveries are verified against it), so creating them is refused with a
//   pointer to the console, where it is pasted.
// - Rotating a secret stays in the console, for the same reason.
//
// Thin adapters (ADR 0025) over `SourceService`, the service the console's `inbound`
// router writes through; it records every change in the audit chain as the person who
// made it.
import { InboundKinds } from '@mocco/common/inbound';
import { z } from 'zod';

import { BadRequestError, ConflictError, ForbiddenError, NotFoundError } from '@backend/domain/errors';
import { InboundSourceNotFoundError } from '@backend/domain/inbound/errors';
import { ToolUnavailableError } from '@backend/domain/mcp/errors';
import { confirmThenApply, openDecision, refused, requireApprovalsWrite } from '@backend/transport/mcp/tools/deciding';
import { asJson, workspaceArg } from '@backend/transport/mcp/tools/runs';

import type { SourceService } from '@backend/domain/inbound/SourceService';
import type { WorkspaceScope } from '@backend/domain/mcp/WorkspaceScope';
import type { DecidingToolDeps } from '@backend/transport/mcp/tools/deciding';
import type { InboundSourceDto } from '@mocco/common/inbound';
import type { CallToolResult, InputRequiredResult, McpServer, ServerContext } from '@modelcontextprotocol/server';

export interface InboundWriteToolDeps extends DecidingToolDeps {
  /** Absent when the server has no `SECRETS_ENCRYPTION_KEYS`; the tools then say so. */
  inbound?: { sources: Pick<SourceService, 'list' | 'create' | 'pause' | 'resume' | 'delete'> };
  scope: WorkspaceScope;
}

type Sources = NonNullable<InboundWriteToolDeps['inbound']>['sources'];

export const InboundWriteTools = {
  create: 'mocco_inbound_sources_create',
  pause: 'mocco_inbound_sources_pause',
  resume: 'mocco_inbound_sources_resume',
  delete: 'mocco_inbound_sources_delete',
} as const;

/** How the tools name what they do, in the opt-in refusals. */
const WORDS = { verb: 'change webhook sources', doing: 'Changing webhook sources' };

/** Where in the console sources are managed. */
const CONSOLE_SOURCES = 'Notifications → Sources in the Mocco console';

const sourceArg = z.uuid().describe('The webhook source, as `mocco_inbound_sources_search` returns it.');

const newSourceInput = z.object({
  workspaceId: workspaceArg,
  kind: z
    .enum([InboundKinds.github, InboundKinds.sentry, InboundKinds.vercel])
    .describe(
      'The service that will deliver. Only `github` can be added here: Sentry and Vercel need a secret pasted in the console.',
    ),
  name: z.string().trim().min(1).max(100).describe('A name for the source, e.g. the repository.'),
});

const sourceInput = z.object({ workspaceId: workspaceArg, sourceId: sourceArg });

export type CreateSourceArgs = z.infer<typeof newSourceInput>;
export type SourceArgs = z.infer<typeof sourceInput>;

function requireSources(deps: InboundWriteToolDeps): Sources {
  if (deps.inbound === undefined) {
    throw new ToolUnavailableError(
      'Inbound webhooks are not configured on this Mocco server: it needs SECRETS_ENCRYPTION_KEYS set',
    );
  }
  return deps.inbound.sources;
}

/** The service's refusals, as the model reads them; anything else is rethrown. */
function changeRefusal(error: unknown): CallToolResult {
  if (
    error instanceof NotFoundError ||
    error instanceof ConflictError ||
    error instanceof BadRequestError ||
    error instanceof ForbiddenError
  ) {
    return refused(error.message);
  }
  throw error;
}

/** A source as the answers show it. `SourceService` never hands out a secret; this picks
 * fields anyway, so nothing added to the DTO later can ride along. */
const sourceSummary = (source: InboundSourceDto) => ({
  id: source.id,
  kind: source.kind,
  name: source.name,
  status: source.status,
  ingestUrl: source.ingestUrl,
});

async function sourceIn(sources: Sources, workspaceId: string, sourceId: string) {
  const listed = await sources.list(workspaceId);
  const source = listed.find(each => each.id === sourceId);
  if (source === undefined) {
    throw new InboundSourceNotFoundError(sourceId);
  }
  return source;
}

/** The checks every changing tool makes before it asks: scope, opt-in and a signing key,
 * the service being here, and the caller being an owner or admin. */
async function openChange(deps: InboundWriteToolDeps, ctx: ServerContext, workspaceArgument?: string) {
  const opened = await openDecision(deps, ctx, workspaceArgument, WORDS);
  if ('content' in opened) {
    return opened;
  }
  const sources = requireSources(deps);
  await deps.scope.requireAdmin(opened.userId, opened.workspaceId);
  return { ...opened, sources };
}

export async function createSource(
  deps: InboundWriteToolDeps,
  args: CreateSourceArgs,
  ctx: ServerContext,
): Promise<CallToolResult | InputRequiredResult> {
  try {
    const opened = await openChange(deps, ctx, args.workspaceId);
    if ('content' in opened) {
      return opened;
    }
    if (args.kind !== InboundKinds.github) {
      return refused(
        `A ${args.kind} source needs the signing secret ${args.kind} shows, and a secret must never pass through an agent. Add it in ${CONSOLE_SOURCES}, where you paste the secret.`,
      );
    }
    const { userId, workspaceId, confirmations, sources } = opened;
    const change = { tool: InboundWriteTools.create, workspaceId, kind: args.kind, name: args.name };
    return await confirmThenApply(ctx, confirmations, change, {
      label: 'Add this source',
      ask: async () =>
        await Promise.resolve(
          [
            'Add a GitHub webhook source to this workspace, as you?',
            `Name: ${args.name}`,
            'Mocco generates its signing secret and does not show it to the agent. To get a secret to paste into GitHub, rotate the source’s secret in the console.',
          ].join('\n'),
        ),
      apply: async () => {
        // A signed confirmation stays valid for five minutes, so the same answer could be
        // sent twice; a source of this kind and name already there means it was.
        const listed = await sources.list(workspaceId);
        const existing = listed.find(each => each.kind === args.kind && each.name === args.name);
        if (existing !== undefined) {
          return refused(
            `A ${args.kind} source named "${args.name}" already exists (${existing.id}), so nothing was added. Pick another name to add a second one.`,
          );
        }
        // The generated secret is dropped here, on purpose: it must not reach the model.
        const { source } = await sources.create(workspaceId, userId, { kind: args.kind, name: args.name });
        return asJson({
          changed: true,
          source: sourceSummary(source),
          secret: `Not shown here. In ${CONSOLE_SOURCES}, rotate this source's secret to get one, then paste it and the ingest URL into the repository's webhook settings in GitHub.`,
        });
      },
    });
  } catch (error) {
    return changeRefusal(error);
  }
}

/** Pause or resume: the same round trip, a different word and service call. */
async function setSourceStatus(
  deps: InboundWriteToolDeps,
  args: SourceArgs,
  ctx: ServerContext,
  to: 'pause' | 'resume',
): Promise<CallToolResult | InputRequiredResult> {
  try {
    const opened = await openChange(deps, ctx, args.workspaceId);
    if ('content' in opened) {
      return opened;
    }
    const { userId, workspaceId, confirmations, sources } = opened;
    const isPause = to === 'pause';
    const tool = isPause ? InboundWriteTools.pause : InboundWriteTools.resume;
    return await confirmThenApply(
      ctx,
      confirmations,
      { tool, workspaceId, sourceId: args.sourceId },
      {
        label: isPause ? 'Pause this source' : 'Resume this source',
        ask: async () => {
          const source = await sourceIn(sources, workspaceId, args.sourceId);
          return [
            isPause ? 'Pause this webhook source, as you?' : 'Resume this webhook source, as you?',
            `Source: ${source.name} (${source.kind}, ${source.id})`,
            `Now: ${source.status}`,
            isPause
              ? 'While paused, its deliveries are refused and nothing is recorded or sent.'
              : 'It accepts deliveries again.',
          ].join('\n');
        },
        apply: async () => {
          const source = isPause
            ? await sources.pause(workspaceId, userId, args.sourceId)
            : await sources.resume(workspaceId, userId, args.sourceId);
          return asJson({ changed: true, source: sourceSummary(source) });
        },
      },
    );
  } catch (error) {
    return changeRefusal(error);
  }
}

export const pauseSource = async (deps: InboundWriteToolDeps, args: SourceArgs, ctx: ServerContext) =>
  await setSourceStatus(deps, args, ctx, 'pause');

export const resumeSource = async (deps: InboundWriteToolDeps, args: SourceArgs, ctx: ServerContext) =>
  await setSourceStatus(deps, args, ctx, 'resume');

export async function deleteSource(
  deps: InboundWriteToolDeps,
  args: SourceArgs,
  ctx: ServerContext,
): Promise<CallToolResult | InputRequiredResult> {
  try {
    const opened = await openChange(deps, ctx, args.workspaceId);
    if ('content' in opened) {
      return opened;
    }
    const { userId, workspaceId, confirmations, sources } = opened;
    const change = { tool: InboundWriteTools.delete, workspaceId, sourceId: args.sourceId };
    return await confirmThenApply(ctx, confirmations, change, {
      label: 'Delete this source',
      ask: async () => {
        const source = await sourceIn(sources, workspaceId, args.sourceId);
        return [
          'Delete this webhook source, as you?',
          `Source: ${source.name} (${source.kind}, ${source.id})`,
          'Its ingest URL stops accepting deliveries and the deliveries it received are deleted. This cannot be undone.',
        ].join('\n');
      },
      apply: async () => {
        await sources.delete(workspaceId, userId, args.sourceId);
        return asJson({ changed: true, deletedSourceId: args.sourceId });
      },
    });
  } catch (error) {
    return changeRefusal(error);
  }
}

const CHANGE_ANNOTATIONS = { readOnlyHint: false, destructiveHint: false, idempotentHint: false } as const;
const SCOPE_CHALLENGE = requireApprovalsWrite(
  'Changing webhook sources needs your permission for this app to make changes as you',
);
const CONFIRMED =
  'The person is asked to confirm in their client first. Only works where the workspace allows agents to make changes, and only for an owner or admin.';

export function registerInboundWriteTools(server: McpServer, deps: InboundWriteToolDeps): void {
  server.registerTool(
    InboundWriteTools.create,
    {
      title: 'Add a GitHub webhook source',
      description: `Add a GitHub webhook source, as the signed-in person. Its signing secret is never returned: the person rotates it in the console to get one to paste into GitHub. Sentry and Vercel sources are refused here, because their secret has to be pasted in the console. ${CONFIRMED}`,
      inputSchema: newSourceInput,
      annotations: CHANGE_ANNOTATIONS,
      scopeChallenge: SCOPE_CHALLENGE,
    },
    async (args, ctx) => await createSource(deps, args, ctx),
  );

  server.registerTool(
    InboundWriteTools.pause,
    {
      title: 'Pause a webhook source',
      description: `Pause a webhook source, so its deliveries are refused and nothing is sent, as the signed-in person. ${CONFIRMED}`,
      inputSchema: sourceInput,
      annotations: { ...CHANGE_ANNOTATIONS, idempotentHint: true },
      scopeChallenge: SCOPE_CHALLENGE,
    },
    async (args, ctx) => await pauseSource(deps, args, ctx),
  );

  server.registerTool(
    InboundWriteTools.resume,
    {
      title: 'Resume a webhook source',
      description: `Resume a paused webhook source, so it accepts deliveries again, as the signed-in person. ${CONFIRMED}`,
      inputSchema: sourceInput,
      annotations: { ...CHANGE_ANNOTATIONS, idempotentHint: true },
      scopeChallenge: SCOPE_CHALLENGE,
    },
    async (args, ctx) => await resumeSource(deps, args, ctx),
  );

  server.registerTool(
    InboundWriteTools.delete,
    {
      title: 'Delete a webhook source',
      description: `Delete a webhook source and the deliveries it received; its ingest URL stops working. As the signed-in person. ${CONFIRMED}`,
      inputSchema: sourceInput,
      annotations: { ...CHANGE_ANNOTATIONS, destructiveHint: true },
      scopeChallenge: SCOPE_CHALLENGE,
    },
    async (args, ctx) => await deleteSource(deps, args, ctx),
  );
}
