// The ONLY file that imports the auth vendor. Everything else consumes the
// neutral surface (./service.ts), so the vendor can be swapped by rewriting
// this file alone (plus the client wrapper on the frontend).
import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { toNodeHandler } from 'better-auth/node';
import { organization } from 'better-auth/plugins';

import { accounts, invitations, members, sessions, users, verifications, workspaces } from '#backend/infra/db/schema';

// Re-exported so the domain services can interpret vendor failures (the org
// plugin throws this on missing/forbidden operations) without importing the
// vendor themselves — this file stays the only vendor importer.
export { isAPIError } from 'better-auth/api';

export interface AuthOptions {
  /** Session signing secret. */
  secret?: string;
  /** Public base URL of the app. */
  baseUrl?: string;
  /** Origins allowed to call the auth endpoints (origin/CSRF check). */
  trustedOrigins?: string[];
}

/** Any drizzle database the adapter accepts (node-postgres in prod, pglite in tests). */
export type AdapterDb = Parameters<typeof drizzleAdapter>[0];

/** Factory — lets tests run the full auth stack against an isolated (pglite) DB. */
export function createProvider(db: AdapterDb, options: AuthOptions = {}) {
  return betterAuth({
    // Explicit injection only — the vendor's own env auto-detection is not relied upon.
    ...(options.secret && { secret: options.secret }),
    ...(options.baseUrl && { baseURL: options.baseUrl }),
    ...(options.trustedOrigins?.length && { trustedOrigins: options.trustedOrigins }),
    database: drizzleAdapter(db, {
      provider: 'pg',
      schema: {
        user: users,
        session: sessions,
        account: accounts,
        verification: verifications,
        organization: workspaces,
        member: members,
        invitation: invitations,
      },
    }),
    // Start with email+password only. Verification emails come later (SMTP);
    // social providers (Google) land as separate PRs.
    emailAndPassword: { enabled: true, requireEmailVerification: false },
    advanced: {
      // uuid PKs are generated by the DB (defaultRandom) — Mocco convention (non-sequential).
      database: { generateId: false },
    },
    // Workspace = organization plugin (members, roles). The invitation MODEL is
    // mapped for plugin compatibility; the invite FLOW ships later. Teams/dynamic
    // roles come later. The plugin requires a unique slug; WorkspaceService fills
    // it with a system uuid, so no create-time slug hook is needed.
    plugins: [organization()],
  });
}

export type Provider = ReturnType<typeof createProvider>;

/** Node-style (req, res) handler for the auth routes — for Pages Router API
 * routes, which are Node handlers rather than Web-standard. The vendor's own
 * bridge (tested cookie/body/stream handling) stays behind this boundary. */
export function toNodeAuthHandler(provider: Provider) {
  return toNodeHandler(provider);
}
export type NodeAuthHandler = ReturnType<typeof toNodeAuthHandler>;
