// What each audit action means, in words, for the places that show the audit log to
// people (Home, the Audit page). A Record over every action, so a new action can't
// ship without a label — the type check fails until it has one.
import { AuditActions } from '@mocco/common/audit';

import type { AuditAction } from '@mocco/common/audit';

export const auditActionLabels: Readonly<Record<AuditAction, string>> = {
  [AuditActions.gateResumed]: 'Deploy gate approved',
  [AuditActions.gateRejected]: 'Deploy gate rejected',
  [AuditActions.credentialIssued]: 'Credential released to a pipeline',
  [AuditActions.credentialDenied]: 'Credential refused to a pipeline',
  [AuditActions.runTriggered]: 'Pipeline run started',
  [AuditActions.approvalRequested]: 'Approval requested',
  [AuditActions.approvalApproved]: 'Approval granted',
  [AuditActions.approvalRejected]: 'Approval rejected',
  [AuditActions.approvalSuperseded]: 'Approval request replaced',
  [AuditActions.approvalExpired]: 'Approval request expired',
  [AuditActions.versionPolicyChanged]: 'App version policy changed',
  [AuditActions.versionPolicyApprovalStale]: 'App version approval went stale',
  [AuditActions.otaCredentialCreated]: 'OTA publishing token added',
  [AuditActions.otaCredentialRotated]: 'OTA publishing token rotated',
  [AuditActions.otaCredentialDeleted]: 'OTA publishing token removed',
  [AuditActions.otaAppCreated]: 'OTA hosting turned on for an app',
  [AuditActions.otaCertAdded]: 'OTA signing certificate added',
  [AuditActions.otaCertRetired]: 'OTA signing certificate retired',
  [AuditActions.otaChannelCreated]: 'OTA channel created',
  [AuditActions.otaChannelPolicyChanged]: 'OTA channel protection changed',
  [AuditActions.otaChannelPolicyApprovalStale]: 'OTA channel approval went stale',
  [AuditActions.otaUploadAuthorized]: 'OTA upload allowed',
  [AuditActions.otaUploadDenied]: 'OTA upload refused',
  [AuditActions.otaTrustPolicyCreated]: 'OTA trusted publisher added',
  [AuditActions.otaTrustPolicyDeleted]: 'OTA trusted publisher removed',
  [AuditActions.otaReleaseUploaded]: 'OTA release uploaded',
  [AuditActions.otaReleaseFailed]: 'OTA release upload failed',
  [AuditActions.otaChannelChanged]: 'OTA channel changed',
  [AuditActions.otaChannelChangeFailed]: 'OTA channel change failed',
  [AuditActions.flagEnvironmentCreated]: 'Flag environment created',
  [AuditActions.flagCreated]: 'Feature flag created',
  [AuditActions.flagDefinitionChanged]: 'Feature flag definition changed',
  [AuditActions.flagFileSynced]: 'Flags file synced from the repository',
  [AuditActions.flagChangesetApplied]: 'Flag change applied',
  [AuditActions.flagChangesetProposed]: 'Flag change proposed',
  [AuditActions.flagChangesetRejected]: 'Flag change rejected',
  [AuditActions.flagChangesetConflicted]: 'Flag change conflicted',
  [AuditActions.flagChangesetWithdrawn]: 'Flag change withdrawn',
  [AuditActions.flagChangesetSuperseded]: 'Flag change replaced by a newer push',
  [AuditActions.flagChangesetExpired]: 'Flag change expired',
  [AuditActions.flagChangeGateChanged]: 'Flag environment protection changed',
  [AuditActions.flagKilled]: 'Kill switch used',
  [AuditActions.flagRestored]: 'Killed flag restored',
  [AuditActions.flagKillRolesChanged]: 'Kill switch roles changed',
  [AuditActions.flagLinkedPipelineChanged]: 'Flag environment pipeline linked',
  [AuditActions.flagClientVisibilityChanged]: 'Flag visibility to apps changed',
  [AuditActions.flagStaleDismissed]: 'Stale flag dismissed',
  [AuditActions.messengerEnabled]: 'Messenger set up',
  [AuditActions.messengerSecretRotated]: 'Messenger identity secret rotated',
  [AuditActions.messengerCategoriesChanged]: 'Messenger categories changed',
  [AuditActions.messengerContactBlocked]: 'Messenger contact blocked',
  [AuditActions.messengerContactErased]: 'Messenger contact erased',
  [AuditActions.helpSiteEnabled]: 'Help center set up',
  [AuditActions.helpSiteChanged]: 'Help center settings changed',
  [AuditActions.helpArticlePublished]: 'Help article published',
  [AuditActions.helpArticleUnpublished]: 'Help article unpublished',
  [AuditActions.helpArticleDeleted]: 'Help article deleted',
  [AuditActions.messengerGuestsChanged]: 'Messenger guest access changed',
  [AuditActions.apiKeyCreated]: 'API key created',
  [AuditActions.apiKeyRevoked]: 'API key revoked',
};
